use std::collections::HashSet;
use std::fmt::Write;
use std::path::Path;

/// Parse ports from docker-compose files and generate override with BIND_IP.
pub fn generate_compose_override(
    repo_dir: &Path,
    worktree_dir: &Path,
    bind_ip: &str,
    compose_files: &[String],
    worktree_env: &indexmap::IndexMap<String, String>,
    branch: &str,
    network_name: Option<&str>,
    service_overrides: Option<&indexmap::IndexMap<String, crate::config::ServiceOverride>>,
    shared_hosts: &[String],
    ws_key: &str,
) {
    let files_to_parse: Vec<std::path::PathBuf> = if compose_files.is_empty() {
        let default = repo_dir.join("docker-compose.yml");
        if default.is_file() { vec![default] } else { return; }
    } else {
        compose_files.iter()
            .map(|f| repo_dir.join(f))
            .filter(|p| p.is_file())
            .collect()
    };

    if files_to_parse.is_empty() {
        return;
    }

    // Parse compose files
    let mut service_ports: indexmap::IndexMap<String, Vec<String>> = indexmap::IndexMap::new();
    let mut hardcoded_container_names: indexmap::IndexMap<String, String> = indexmap::IndexMap::new();
    let mut service_depends: indexmap::IndexMap<String, Vec<String>> = indexmap::IndexMap::new();
    let mut all_service_names: HashSet<String> = HashSet::new();

    for f in &files_to_parse {
        parse_compose_file(f, &mut service_ports, &mut hardcoded_container_names,
                          &mut service_depends, &mut all_service_names, bind_ip);
    }

    if service_ports.is_empty() && worktree_env.is_empty() {
        return;
    }

    let branch_safe = super::branch_safe(branch);
    let resolved_env: Vec<(String, String)> = super::resolve_env_templates(worktree_env, bind_ip, &branch_safe, branch, ws_key);

    // Add workspace-specific proxy hostnames to shared_hosts
    // Computed from env values — any http://*.tncli.test URL gets its hostname added as extra_host
    let mut all_hosts: Vec<String> = shared_hosts.to_vec();
    for (_, val) in &resolved_env {
        if let Some(rest) = val.strip_prefix("http://") {
            let host = rest.split(':').next().unwrap_or(rest).split('/').next().unwrap_or(rest);
            if host.ends_with(".tncli.test") && !all_hosts.iter().any(|h| h == host) {
                all_hosts.push(host.to_string());
            }
        }
    }
    let shared_hosts = &all_hosts;

    let project_name = compose_project_name(worktree_dir);

    let mut output = String::with_capacity(4096);
    output.push_str("# Auto-generated by tncli for worktree. Do not commit.\n");
    let _ = write!(output, "name: {project_name}\n");

    if let Some(net) = network_name {
        let _ = write!(output, "\nnetworks:\n  {}:\n    external: true\n", net);
    }

    output.push_str("\nservices:\n");

    let merged_overrides: indexmap::IndexMap<String, crate::config::ServiceOverride> =
        service_overrides.cloned().unwrap_or_default();
    let service_overrides = Some(&merged_overrides);

    let svc_override_names: Vec<String> = service_overrides
        .map(|so| so.keys().cloned().collect())
        .unwrap_or_default();

    let mut all_svc_merged: Vec<String> = all_service_names.iter().cloned().collect();
    for name in &svc_override_names {
        if !all_service_names.contains(name) {
            all_svc_merged.push(name.clone());
        }
    }

    let disabled_svcs: HashSet<String> = service_overrides
        .map(|so| so.iter()
            .filter(|(_, ov)| !ov.profiles.is_empty())
            .map(|(name, _)| name.clone())
            .collect())
        .unwrap_or_default();

    for svc in &all_svc_merged {
        write_service_override(
            &mut output, svc, &service_ports, &resolved_env, network_name,
            service_overrides, &hardcoded_container_names, &service_depends,
            &disabled_svcs, &project_name, shared_hosts, bind_ip,
        );
    }

    let override_path = worktree_dir.join("docker-compose.override.yml");
    let _ = std::fs::write(&override_path, &output);

    // If dip.yml exists, create dip.override.yml
    let dip_path = worktree_dir.join("dip.yml");
    if dip_path.is_file() {
        let dip_override = worktree_dir.join("dip.override.yml");
        let _ = std::fs::write(dip_override,
            "version: '6.1'\n\ncompose:\n  files:\n    - docker-compose.yml\n    - docker-compose.override.yml\n"
        );
    }
}

/// Setup main dir as worktree-like environment with the given bind_ip.
pub fn setup_main_as_worktree(
    repo_dir: &Path,
    bind_ip: &str,
    compose_files: &[String],
    worktree_env: &indexmap::IndexMap<String, String>,
    branch: &str,
    service_overrides: Option<&indexmap::IndexMap<String, crate::config::ServiceOverride>>,
    shared_hosts: &[String],
    ws_key: &str,
) {
    generate_compose_override(repo_dir, repo_dir, bind_ip, compose_files, worktree_env, branch, None, service_overrides, shared_hosts, ws_key);
}

/// Get docker-compose project name from worktree path.
fn compose_project_name(worktree_dir: &Path) -> String {
    let dir_name = worktree_dir.file_name()
        .map(|n| n.to_string_lossy().to_string())
        .unwrap_or_default();
    let parent_name = worktree_dir.parent()
        .and_then(|p| p.file_name())
        .map(|n| n.to_string_lossy().to_string())
        .unwrap_or_default();
    if parent_name.starts_with("workspace--") {
        let ws_name = parent_name.trim_start_matches("workspace--");
        format!("{dir_name}-{ws_name}")
    } else {
        dir_name
    }
}

fn parse_compose_file(
    f: &Path,
    service_ports: &mut indexmap::IndexMap<String, Vec<String>>,
    hardcoded_container_names: &mut indexmap::IndexMap<String, String>,
    service_depends: &mut indexmap::IndexMap<String, Vec<String>>,
    all_service_names: &mut HashSet<String>,
    bind_ip: &str,
) {
    let content = match std::fs::read_to_string(f) {
        Ok(c) => c,
        Err(_) => return,
    };
    let yaml: serde_yaml::Value = match serde_yaml::from_str(&content) {
        Ok(v) => v,
        Err(_) => return,
    };
    let Some(services) = yaml.get("services").and_then(|s| s.as_mapping()) else { return };

    for (name, svc) in services {
        let Some(name) = name.as_str() else { continue };
        all_service_names.insert(name.to_string());

        if let Some(cn) = svc.get("container_name").and_then(|c| c.as_str()) {
            hardcoded_container_names.insert(name.to_string(), cn.to_string());
        }

        if let Some(deps) = svc.get("depends_on") {
            let dep_list: Vec<String> = if let Some(seq) = deps.as_sequence() {
                seq.iter().filter_map(|v| v.as_str().map(|s| s.to_string())).collect()
            } else if let Some(map) = deps.as_mapping() {
                map.keys().filter_map(|k| k.as_str().map(|s| s.to_string())).collect()
            } else {
                Vec::new()
            };
            if !dep_list.is_empty() {
                service_depends.insert(name.to_string(), dep_list);
            }
        }

        if let Some(ports) = svc.get("ports").and_then(|p| p.as_sequence()) {
            for port in ports {
                let port_str = match port.as_str() {
                    Some(s) => s.to_string(),
                    None => match port.as_i64() {
                        Some(n) => n.to_string(),
                        None => continue,
                    },
                };
                let parts: Vec<&str> = port_str.split(':').collect();
                let new_port = match parts.len() {
                    2 => format!("{bind_ip}:{port_str}"),
                    3 => format!("{bind_ip}:{}:{}", parts[1], parts[2]),
                    _ => continue,
                };
                service_ports.entry(name.to_string()).or_default().push(new_port);
            }
        }
    }
}

#[allow(clippy::too_many_arguments)]
fn write_service_override(
    output: &mut String,
    svc: &str,
    service_ports: &indexmap::IndexMap<String, Vec<String>>,
    resolved_env: &[(String, String)],
    network_name: Option<&str>,
    service_overrides: Option<&indexmap::IndexMap<String, crate::config::ServiceOverride>>,
    hardcoded_container_names: &indexmap::IndexMap<String, String>,
    service_depends: &indexmap::IndexMap<String, Vec<String>>,
    disabled_svcs: &HashSet<String>,
    project_name: &str,
    shared_hosts: &[String],
    bind_ip: &str,
) {
    let has_ports = service_ports.contains_key(svc);
    let needs_env = !resolved_env.is_empty();
    let needs_network = network_name.is_some();
    let has_svc_override = service_overrides.and_then(|so| so.get(svc)).is_some();
    let has_hardcoded_name = hardcoded_container_names.contains_key(svc);
    let needs_depends_override = !disabled_svcs.is_empty() && !disabled_svcs.contains(svc);

    if !has_ports && !needs_env && !needs_network && !has_svc_override && !has_hardcoded_name && !needs_depends_override {
        return;
    }

    let _ = write!(output, "  {svc}:\n");

    if hardcoded_container_names.contains_key(svc) {
        let new_name = format!("{project_name}-{svc}");
        let _ = write!(output, "    container_name: {new_name}\n");
    }

    if needs_depends_override {
        if let Some(deps) = service_depends.get(svc) {
            let filtered: Vec<&String> = deps.iter()
                .filter(|d| !disabled_svcs.contains(*d))
                .collect();
            if filtered.is_empty() {
                output.push_str("    depends_on: !override []\n");
            } else {
                output.push_str("    depends_on: !override\n");
                for d in &filtered {
                    let _ = write!(output, "      - {d}\n");
                }
            }
        } else {
            output.push_str("    depends_on: !override []\n");
        }
    }

    if let Some(svc_ov) = service_overrides.and_then(|so| so.get(svc)) {
        if !svc_ov.profiles.is_empty() {
            output.push_str("    profiles:\n");
            for p in &svc_ov.profiles {
                let _ = write!(output, "      - \"{p}\"\n");
            }
        }
        if let Some(mem) = &svc_ov.mem_limit {
            let _ = write!(output, "    mem_limit: {mem}\n");
        }
    }

    if let Some(ports) = service_ports.get(svc) {
        output.push_str("    ports: !override\n");
        for port in ports {
            let _ = write!(output, "      - \"{port}\"\n");
        }
    }

    let mut env_map: Vec<(String, String)> = resolved_env.to_vec();
    if let Some(svc_ov) = service_overrides.and_then(|so| so.get(svc)) {
        for (k, v) in &svc_ov.environment {
            if let Some(existing) = env_map.iter_mut().find(|(ek, _)| ek == k) {
                existing.1 = v.clone();
            } else {
                env_map.push((k.clone(), v.clone()));
            }
        }
    }
    if !env_map.is_empty() {
        output.push_str("    environment:\n");
        for (k, v) in &env_map {
            let _ = write!(output, "      {k}: \"{v}\"\n");
        }
    }

    let has_extra_hosts = !shared_hosts.is_empty() || !bind_ip.is_empty();
    if has_extra_hosts {
        output.push_str("    extra_hosts:\n");
        for host in shared_hosts {
            let _ = write!(output, "      - \"{}:host-gateway\"\n", host);
        }
        if !bind_ip.is_empty() {
            let _ = write!(output, "      - \"bind.local:host-gateway\"\n");
        }
    }

    if let Some(net) = network_name {
        let _ = write!(output, "    networks:\n      - default\n      - {}\n", net);
    }
}
