use anyhow::Result;
use std::collections::HashSet;
use std::path::{Path, PathBuf};
use std::process::Command;

/// Copy files from parent repo to worktree based on user-configured list.
/// Supports simple glob: `apps/*/.env` matches `apps/portal/.env`, `apps/crm/.env`, etc.
pub fn copy_files(repo_dir: &Path, worktree_dir: &Path, patterns: &[String]) {
    for pattern in patterns {
        if pattern.contains('*') {
            let full_pattern = format!("{}/{}", repo_dir.display(), pattern);
            if let Ok(paths) = glob_simple(&full_pattern, repo_dir) {
                for rel_path in &paths {
                    copy_single_file(&repo_dir.join(rel_path), &worktree_dir.join(rel_path));
                }
            }
        } else {
            copy_single_file(&repo_dir.join(pattern), &worktree_dir.join(pattern));
        }
    }
}

fn copy_single_file(src: &Path, dest: &Path) {
    if src.is_file() && !dest.exists() {
        if let Some(parent) = dest.parent() {
            let _ = std::fs::create_dir_all(parent);
        }
        let _ = std::fs::copy(src, dest);
    }
}

/// Apply env overrides by writing env file (e.g. .env.local) in each dir that has .env files.
pub fn apply_env_overrides(worktree_dir: &Path, env_overrides: &[(String, String)], env_file_name: &str) {
    if env_overrides.is_empty() {
        return;
    }

    let env_dirs = find_env_dirs(worktree_dir);

    for dir in &env_dirs {
        let all_keys = collect_env_keys(dir, env_file_name);
        let mut lines: Vec<String> = vec!["# Auto-generated by tncli. Do not commit.".into()];
        for (key, value) in env_overrides {
            if all_keys.contains(key.as_str()) {
                lines.push(format!("{key}={value}"));
            }
        }
        if lines.len() > 1 {
            let local_path = dir.join(env_file_name);
            let _ = std::fs::write(&local_path, lines.join("\n") + "\n");
        }
    }
}

/// Find directories containing .env files (top-level + apps/*).
fn find_env_dirs(worktree_dir: &Path) -> Vec<PathBuf> {
    let mut dirs = Vec::new();

    if worktree_dir.join(".env").is_file() || worktree_dir.join(".env.development").is_file() {
        dirs.push(worktree_dir.to_path_buf());
    }

    if let Ok(entries) = std::fs::read_dir(worktree_dir.join("apps")) {
        for entry in entries.flatten() {
            if entry.file_type().is_ok_and(|t| t.is_dir()) {
                let app_dir = entry.path();
                if app_dir.join(".env").is_file() {
                    dirs.push(app_dir);
                }
            }
        }
    }
    dirs
}

/// Collect all env keys from .env* files in a directory.
fn collect_env_keys(dir: &Path, exclude_file: &str) -> HashSet<String> {
    let mut keys = HashSet::new();
    if let Ok(entries) = std::fs::read_dir(dir) {
        for entry in entries.flatten() {
            let name = entry.file_name();
            let name_str = name.to_string_lossy();
            if name_str.starts_with(".env") && name_str != exclude_file
                && entry.file_type().is_ok_and(|t| t.is_file())
            {
                if let Ok(content) = std::fs::read_to_string(entry.path()) {
                    for line in content.lines() {
                        let line = line.trim();
                        if !line.starts_with('#') && !line.is_empty() {
                            if let Some(key) = line.split('=').next() {
                                keys.insert(key.trim().to_string());
                            }
                        }
                    }
                }
            }
        }
    }
    keys
}

/// Run setup commands in worktree dir (foreground, prints output).
#[allow(dead_code)]
pub fn run_setup_foreground(worktree_dir: &Path, commands: &[String]) {
    if commands.is_empty() {
        return;
    }
    let dir_name = worktree_dir.file_name().unwrap_or_default().to_string_lossy();
    for cmd in commands {
        eprintln!("  [setup] {dir_name}: {cmd}");
        let _ = Command::new("zsh")
            .args(["-ic", cmd])
            .current_dir(worktree_dir)
            .status();
    }
}

/// Write .env.tncli file in worktree dir with BIND_IP.
pub fn write_env_file(worktree_path: &Path, ip: &str) -> Result<()> {
    let env_path = worktree_path.join(".env.tncli");
    std::fs::write(&env_path, format!("BIND_IP={ip}\n"))?;
    Ok(())
}

/// Simple glob using shell expansion (avoids adding glob crate).
fn glob_simple(pattern: &str, repo_dir: &Path) -> Result<Vec<String>> {
    let parts: Vec<&str> = pattern.split('*').collect();
    if parts.len() != 2 {
        return Ok(Vec::new());
    }
    let output = Command::new("bash")
        .args(["-c", &format!("cd '{}' && ls {} 2>/dev/null", repo_dir.display(), pattern.replace(&format!("{}/", repo_dir.display()), ""))])
        .output()?;
    let files: Vec<String> = String::from_utf8_lossy(&output.stdout)
        .lines()
        .map(|l| l.trim())
        .filter(|l| !l.is_empty())
        .map(|l| l.to_string())
        .collect();
    Ok(files)
}

/// Ensure docker-compose.override.yml is in global gitignore.
pub fn ensure_global_gitignore() {
    let home = match std::env::var("HOME") {
        Ok(h) => h,
        Err(_) => return,
    };
    let gitignore_path = format!("{home}/.gitignore_global");

    let excludes = Command::new("git")
        .args(["config", "--global", "core.excludesfile"])
        .output()
        .ok()
        .and_then(|o| if o.status.success() { String::from_utf8(o.stdout).ok() } else { None })
        .unwrap_or_default()
        .trim()
        .to_string();

    if excludes.is_empty() {
        let _ = Command::new("git")
            .args(["config", "--global", "core.excludesfile", &gitignore_path])
            .output();
    }

    let target = if excludes.is_empty() { &gitignore_path } else { &excludes };
    let content = std::fs::read_to_string(target).unwrap_or_default();

    let tncli_files = [
        "docker-compose.override.yml",
        "docker-compose.shared.yml",
        "dip.override.yml",
        ".env.tncli",
        ".env.local",
        ".env.*.local",
    ];
    let mut to_add = Vec::new();
    for file in &tncli_files {
        if !content.contains(file) {
            to_add.push(*file);
        }
    }
    if !to_add.is_empty() {
        use std::io::Write;
        if let Ok(mut f) = std::fs::OpenOptions::new().create(true).append(true).open(target) {
            if !content.contains("# tncli") {
                let _ = writeln!(f, "\n# tncli worktree");
            }
            for file in to_add {
                let _ = writeln!(f, "{file}");
            }
        }
    }
}
