use std::collections::{HashMap, HashSet};
use std::fmt::Write;
use std::path::{Path, PathBuf};
use std::process::Command;

// ── Shared Compose Generation ──

/// Generate docker-compose.shared.yml from top-level shared_services config.
pub fn generate_shared_compose(
    config_dir: &Path,
    session: &str,
    shared_services: &indexmap::IndexMap<String, crate::config::SharedServiceDef>,
) -> PathBuf {
    let mut output = String::with_capacity(4096);
    output.push_str("# Auto-generated by tncli. Do not edit.\n");
    let _ = write!(output, "name: {session}-shared\n\n");

    let mut volume_names: Vec<String> = Vec::new();
    let mut volume_set: HashSet<String> = HashSet::new();

    output.push_str("services:\n");
    for (name, svc) in shared_services {
        let instances = if svc.capacity.is_some() { max_instance_count(name) } else { 1 };

        for inst in 0..instances {
            let svc_name = if inst == 0 { name.clone() } else { format!("{name}-{}", inst + 1) };
            let _ = write!(output, "  {svc_name}:\n");
            let _ = write!(output, "    image: {}\n", svc.image);

            if let Some(cmd) = &svc.command {
                let _ = write!(output, "    command: {cmd}\n");
            }

            if !svc.ports.is_empty() {
                output.push_str("    ports:\n");
                for port in &svc.ports {
                    let adjusted = if inst > 0 {
                        let parts: Vec<&str> = port.split(':').collect();
                        if parts.len() == 2 {
                            if let Ok(host_port) = parts[0].parse::<u16>() {
                                format!("{}:{}", host_port + inst as u16, parts[1])
                            } else { port.clone() }
                        } else { port.clone() }
                    } else { port.clone() };
                    let _ = write!(output, "      - \"{adjusted}\"\n");
                }
            }

            if !svc.environment.is_empty() {
                output.push_str("    environment:\n");
                for (k, v) in &svc.environment {
                    let _ = write!(output, "      {k}: \"{v}\"\n");
                }
            }

            if !svc.volumes.is_empty() {
                output.push_str("    volumes:\n");
                for vol in &svc.volumes {
                    let adjusted_vol = if inst > 0 {
                        let parts: Vec<&str> = vol.splitn(2, ':').collect();
                        if parts.len() == 2 && !parts[0].starts_with('.') && !parts[0].starts_with('/') {
                            let vol_name = format!("{}-{}", parts[0], inst + 1);
                            format!("{vol_name}:{}", parts[1])
                        } else { vol.clone() }
                    } else { vol.clone() };
                    let _ = write!(output, "      - {adjusted_vol}\n");
                    if let Some(vol_name) = adjusted_vol.split(':').next() {
                        if !vol_name.starts_with('.') && !vol_name.starts_with('/') && volume_set.insert(vol_name.to_string()) {
                            volume_names.push(vol_name.to_string());
                        }
                    }
                }
            }

            if let Some(hc) = &svc.healthcheck {
                output.push_str("    healthcheck:\n");
                match &hc.test {
                    serde_yaml::Value::String(s) => {
                        let _ = write!(output, "      test: {s}\n");
                    }
                    other => {
                        if let Ok(yaml) = serde_yaml::to_string(other) {
                            let _ = write!(output, "      test: {}", yaml.trim_start_matches("---\n"));
                        }
                    }
                }
                let _ = write!(output, "      interval: {}\n", hc.interval);
                let _ = write!(output, "      timeout: {}\n", hc.timeout);
                let _ = write!(output, "      retries: {}\n", hc.retries);
            }

            output.push_str("    restart: unless-stopped\n");
            output.push('\n');
        }
    }

    if !volume_names.is_empty() {
        output.push_str("volumes:\n");
        for vol in &volume_names {
            let _ = write!(output, "  {vol}:\n    driver: local\n");
        }
    }

    let path = config_dir.join("docker-compose.shared.yml");
    let _ = std::fs::write(&path, &output);
    path
}

/// Start shared services from the generated compose file.
pub fn start_shared_services(config_dir: &Path, session: &str, service_names: &[&str]) {
    let compose_file = config_dir.join("docker-compose.shared.yml");
    if !compose_file.is_file() {
        return;
    }
    let _ = Command::new("docker")
        .args(["compose", "-f", &compose_file.to_string_lossy(), "-p", &format!("{session}-shared"), "up", "-d"])
        .args(service_names)
        .current_dir(config_dir)
        .output();
}

/// Create database for worktree on a shared postgres instance.
pub fn create_shared_db(host: &str, port: u16, db_name: &str, user: &str, password: &str) -> String {
    let extra_host = format!("--add-host={host}:host-gateway");
    let conn_url = format!("postgresql://{user}:{password}@{host}:{port}/postgres");
    let create_sql = format!("CREATE DATABASE \"{db_name}\"");

    let output = Command::new("docker")
        .args(["run", "--rm", &extra_host, "postgres:16-alpine", "psql", &conn_url, "-c", &create_sql])
        .output();

    match output {
        Ok(o) => {
            let stderr = String::from_utf8_lossy(&o.stderr);
            if o.status.success() {
                format!("created db: {db_name}")
            } else if stderr.contains("already exists") {
                format!("db exists: {db_name}")
            } else {
                format!("warning: {db_name}: {}", stderr.trim())
            }
        }
        Err(e) => format!("error creating DB: {e}"),
    }
}

/// Drop database on shared postgres instance.
pub fn drop_shared_db(host: &str, port: u16, db_name: &str, user: &str, password: &str) {
    let extra_host = format!("--add-host={host}:host-gateway");
    let conn_url = format!("postgresql://{user}:{password}@{host}:{port}/postgres");
    let drop_sql = format!("DROP DATABASE IF EXISTS \"{db_name}\"");

    let _ = Command::new("docker")
        .args(["run", "--rm", &extra_host, "postgres:16-alpine", "psql", &conn_url, "-c", &drop_sql])
        .stdin(std::process::Stdio::null())
        .stdout(std::process::Stdio::null())
        .stderr(std::process::Stdio::null())
        .status();
}

// ── Slot Allocation ──

const SLOT_STATE_FILE: &str = ".tncli/shared_slots.json";

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct SlotAllocation {
    pub instance: usize,
    pub slot: usize,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize, Default)]
pub struct ServiceSlots {
    pub slots: HashMap<String, SlotAllocation>,
    pub instance_count: usize,
}

fn slot_state_path() -> PathBuf {
    let home = std::env::var("HOME").unwrap_or_else(|_| "/tmp".into());
    PathBuf::from(home).join(SLOT_STATE_FILE)
}

pub fn load_slot_allocations() -> HashMap<String, ServiceSlots> {
    let path = slot_state_path();
    std::fs::read_to_string(&path)
        .ok()
        .and_then(|s| serde_json::from_str(&s).ok())
        .unwrap_or_default()
}

fn save_slot_allocations(allocs: &HashMap<String, ServiceSlots>) {
    let path = slot_state_path();
    if let Some(parent) = path.parent() {
        let _ = std::fs::create_dir_all(parent);
    }
    if let Ok(json) = serde_json::to_string_pretty(allocs) {
        let _ = std::fs::write(&path, json);
    }
}

/// File-lock for slot allocation (same pattern as IP lock).
fn with_slot_lock<F, R>(f: F) -> R
where
    F: FnOnce() -> R,
{
    use std::fs::OpenOptions;
    use std::io::Write;

    let lock_path = {
        let home = std::env::var("HOME").unwrap_or_else(|_| "/tmp".into());
        PathBuf::from(home).join(".tncli/slots.lock")
    };
    if let Some(parent) = lock_path.parent() {
        let _ = std::fs::create_dir_all(parent);
    }

    let lockfile = loop {
        match OpenOptions::new().write(true).create_new(true).open(&lock_path) {
            Ok(mut f) => { let _ = write!(f, "{}", std::process::id()); break f; }
            Err(_) => {
                if let Ok(meta) = std::fs::metadata(&lock_path) {
                    if let Ok(modified) = meta.modified() {
                        if modified.elapsed().unwrap_or_default() > std::time::Duration::from_secs(10) {
                            let _ = std::fs::remove_file(&lock_path);
                            continue;
                        }
                    }
                }
                std::thread::sleep(std::time::Duration::from_millis(50));
            }
        }
    };

    let result = f();
    drop(lockfile);
    let _ = std::fs::remove_file(&lock_path);
    result
}

/// Allocate a slot on a shared service instance. Thread-safe via file lock.
/// Returns (instance_index, slot_index, port).
pub fn allocate_slot(service_name: &str, worktree_key: &str, capacity: u16, base_port: u16) -> (usize, usize, u16) {
    with_slot_lock(|| allocate_slot_inner(service_name, worktree_key, capacity, base_port))
}

fn allocate_slot_inner(service_name: &str, worktree_key: &str, capacity: u16, base_port: u16) -> (usize, usize, u16) {
    let mut allocs = load_slot_allocations();
    let svc = allocs.entry(service_name.to_string()).or_insert_with(|| ServiceSlots {
        slots: HashMap::new(),
        instance_count: 1,
    });

    if let Some(existing) = svc.slots.get(worktree_key) {
        let port = base_port + existing.instance as u16;
        return (existing.instance, existing.slot, port);
    }

    let cap = capacity as usize;
    for inst in 0..svc.instance_count {
        let used_in_inst = svc.slots.values().filter(|a| a.instance == inst).count();
        if used_in_inst < cap {
            let used_slots: HashSet<usize> = svc.slots.values()
                .filter(|a| a.instance == inst)
                .map(|a| a.slot)
                .collect();
            let slot = (0..cap).find(|s| !used_slots.contains(s)).unwrap_or(0);
            svc.slots.insert(worktree_key.to_string(), SlotAllocation { instance: inst, slot });
            save_slot_allocations(&allocs);
            let port = base_port + inst as u16;
            return (inst, slot, port);
        }
    }

    let new_inst = svc.instance_count;
    svc.instance_count += 1;
    svc.slots.insert(worktree_key.to_string(), SlotAllocation { instance: new_inst, slot: 0 });
    save_slot_allocations(&allocs);
    let port = base_port + new_inst as u16;
    (new_inst, 0, port)
}

/// Release slot when worktree is deleted. Thread-safe via file lock.
pub fn release_slot(service_name: &str, worktree_key: &str) {
    with_slot_lock(|| release_slot_inner(service_name, worktree_key));
}

fn release_slot_inner(service_name: &str, worktree_key: &str) {
    let mut allocs = load_slot_allocations();
    if let Some(svc) = allocs.get_mut(service_name) {
        svc.slots.remove(worktree_key);
        while svc.instance_count > 1 {
            let last = svc.instance_count - 1;
            if svc.slots.values().any(|a| a.instance == last) {
                break;
            }
            svc.instance_count -= 1;
        }
    }
    save_slot_allocations(&allocs);
}

/// Get the maximum instance_count for compose generation.
pub fn max_instance_count(service_name: &str) -> usize {
    load_slot_allocations()
        .get(service_name)
        .map(|s| s.instance_count)
        .unwrap_or(1)
}
