package services

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/toantran292/tncli/internal/config"
	"gopkg.in/yaml.v3"
)

// GenerateComposeOverride generates docker-compose.override.yml with BIND_IP.
func GenerateComposeOverride(
	repoDir, worktreeDir, bindIP string,
	composeFiles []string,
	worktreeEnv map[string]string,
	branch string,
	networkName string,
	serviceOverrides map[string]*config.ServiceOverride,
	sharedHosts []string,
	wsKey string,
	cfg *config.Config,
	databases []string,
) {
	// Determine files to parse
	var filesToParse []string
	if len(composeFiles) == 0 {
		def := filepath.Join(repoDir, "docker-compose.yml")
		if fileExists(def) {
			filesToParse = []string{def}
		} else {
			return
		}
	} else {
		for _, f := range composeFiles {
			p := filepath.Join(repoDir, f)
			if fileExists(p) {
				filesToParse = append(filesToParse, p)
			}
		}
	}
	if len(filesToParse) == 0 {
		return
	}

	// Parse compose files
	servicePorts := make(map[string][]string)
	hardcodedNames := make(map[string]string)
	serviceDepends := make(map[string][]string)
	allSvcNames := make(map[string]bool)

	for _, f := range filesToParse {
		parseComposeFile(f, servicePorts, hardcodedNames, serviceDepends, allSvcNames, bindIP)
	}

	if len(servicePorts) == 0 && len(worktreeEnv) == 0 {
		return
	}

	branchSafe := BranchSafe(branch)
	// Merge env: global → worktree
	mergedEnv := make(map[string]string)
	for k, v := range cfg.Env {
		mergedEnv[k] = v
	}
	for k, v := range worktreeEnv {
		mergedEnv[k] = v
	}
	resolvedEnv := ResolveEnvTemplates(mergedEnv, cfg, bindIP, branchSafe, branch, wsKey)

	// Resolve {{db:N}}
	var dbNames []string
	for _, tpl := range databases {
		name := strings.ReplaceAll(tpl, "{{branch_safe}}", branchSafe)
		name = strings.ReplaceAll(name, "{{branch}}", branch)
		dbNames = append(dbNames, cfg.Session+"_"+name)
	}
	for i, kv := range resolvedEnv {
		resolvedEnv[i] = [2]string{kv[0], ResolveDBTemplates(kv[1], dbNames)}
	}

	// Extract *.tncli.test hostnames from env values for extra_hosts
	allHosts := append([]string{}, sharedHosts...)
	for _, kv := range resolvedEnv {
		val := kv[1]
		if idx := strings.Index(val, "://"); idx >= 0 {
			rest := val[idx+3:]
			afterAuth := rest
			if at := strings.LastIndex(rest, "@"); at >= 0 {
				afterAuth = rest[at+1:]
			}
			host := strings.SplitN(afterAuth, ":", 2)[0]
			host = strings.SplitN(host, "/", 2)[0]
			if strings.HasSuffix(host, ".tncli.test") && !containsStr(allHosts, host) {
				allHosts = append(allHosts, host)
			}
		}
	}

	projectName := composeProjectName(worktreeDir)

	var b strings.Builder
	b.WriteString("# Auto-generated by tncli for worktree. Do not commit.\n")
	fmt.Fprintf(&b, "name: %s\n", projectName)

	if networkName != "" {
		fmt.Fprintf(&b, "\nnetworks:\n  %s:\n    external: true\n", networkName)
	}

	b.WriteString("\nservices:\n")

	// Merge all service names + override names
	var allSvcMerged []string
	for name := range allSvcNames {
		allSvcMerged = append(allSvcMerged, name)
	}
	if serviceOverrides != nil {
		for name := range serviceOverrides {
			if !allSvcNames[name] {
				allSvcMerged = append(allSvcMerged, name)
			}
		}
	}

	// Build disabled set
	disabledSvcs := make(map[string]bool)
	if serviceOverrides != nil {
		for name, ov := range serviceOverrides {
			if len(ov.Profiles) > 0 {
				disabledSvcs[name] = true
			}
		}
	}

	for _, svc := range allSvcMerged {
		writeServiceOverride(&b, svc, servicePorts, resolvedEnv, networkName,
			serviceOverrides, hardcodedNames, serviceDepends,
			disabledSvcs, projectName, allHosts, bindIP)
	}

	overridePath := filepath.Join(worktreeDir, "docker-compose.override.yml")
	_ = os.WriteFile(overridePath, []byte(b.String()), 0o644)

	// dip.yml support
	if fileExists(filepath.Join(worktreeDir, "dip.yml")) {
		_ = os.WriteFile(filepath.Join(worktreeDir, "dip.override.yml"),
			[]byte("version: '6.1'\n\ncompose:\n  files:\n    - docker-compose.yml\n    - docker-compose.override.yml\n"), 0o644)
	}
}

// SetupMainAsWorktree sets up main dir with worktree-like env.
func SetupMainAsWorktree(repoDir, bindIP string, composeFiles []string, worktreeEnv map[string]string, branch string, serviceOverrides map[string]*config.ServiceOverride, sharedHosts []string, wsKey string, cfg *config.Config, databases []string) {
	GenerateComposeOverride(repoDir, repoDir, bindIP, composeFiles, worktreeEnv, branch, "", serviceOverrides, sharedHosts, wsKey, cfg, databases)
}

func composeProjectName(worktreeDir string) string {
	dirName := filepath.Base(worktreeDir)
	parentName := filepath.Base(filepath.Dir(worktreeDir))
	if strings.HasPrefix(parentName, "workspace--") {
		wsName := strings.TrimPrefix(parentName, "workspace--")
		return dirName + "-" + wsName
	}
	return dirName
}

func parseComposeFile(f string, servicePorts map[string][]string, hardcodedNames map[string]string, serviceDepends map[string][]string, allSvcNames map[string]bool, bindIP string) {
	data, err := os.ReadFile(f)
	if err != nil {
		return
	}
	var doc yaml.Node
	if yaml.Unmarshal(data, &doc) != nil {
		return
	}
	if doc.Kind != yaml.DocumentNode || len(doc.Content) == 0 {
		return
	}
	root := doc.Content[0]
	if root.Kind != yaml.MappingNode {
		return
	}

	// Find services key
	for i := 0; i+1 < len(root.Content); i += 2 {
		if root.Content[i].Value != "services" {
			continue
		}
		svcsNode := root.Content[i+1]
		if svcsNode.Kind != yaml.MappingNode {
			continue
		}

		for j := 0; j+1 < len(svcsNode.Content); j += 2 {
			name := svcsNode.Content[j].Value
			svcNode := svcsNode.Content[j+1]
			allSvcNames[name] = true

			if svcNode.Kind != yaml.MappingNode {
				continue
			}

			for k := 0; k+1 < len(svcNode.Content); k += 2 {
				key := svcNode.Content[k].Value
				val := svcNode.Content[k+1]

				switch key {
				case "container_name":
					if val.Kind == yaml.ScalarNode {
						hardcodedNames[name] = val.Value
					}
				case "depends_on":
					var deps []string
					if val.Kind == yaml.SequenceNode {
						for _, item := range val.Content {
							if item.Kind == yaml.ScalarNode {
								deps = append(deps, item.Value)
							}
						}
					} else if val.Kind == yaml.MappingNode {
						for d := 0; d+1 < len(val.Content); d += 2 {
							deps = append(deps, val.Content[d].Value)
						}
					}
					if len(deps) > 0 {
						serviceDepends[name] = deps
					}
				case "ports":
					if val.Kind != yaml.SequenceNode {
						continue
					}
					for _, portNode := range val.Content {
						portStr := portNode.Value
						if portStr == "" {
							continue
						}
						parts := strings.Split(portStr, ":")
						var newPort string
						switch len(parts) {
						case 2:
							newPort = fmt.Sprintf("%s:%s", bindIP, portStr)
						case 3:
							newPort = fmt.Sprintf("%s:%s:%s", bindIP, parts[1], parts[2])
						default:
							continue
						}
						servicePorts[name] = append(servicePorts[name], newPort)
					}
				}
			}
		}
	}
}

func writeServiceOverride(b *strings.Builder, svc string, servicePorts map[string][]string, resolvedEnv [][2]string, networkName string, serviceOverrides map[string]*config.ServiceOverride, hardcodedNames map[string]string, serviceDepends map[string][]string, disabledSvcs map[string]bool, projectName string, sharedHosts []string, bindIP string) {
	hasPorts := len(servicePorts[svc]) > 0
	needsEnv := len(resolvedEnv) > 0
	needsNetwork := networkName != ""
	var svcOv *config.ServiceOverride
	if serviceOverrides != nil {
		svcOv = serviceOverrides[svc]
	}
	hasSvcOverride := svcOv != nil
	_, hasHardcodedName := hardcodedNames[svc]
	needsDependsOverride := len(disabledSvcs) > 0 && !disabledSvcs[svc]

	if !hasPorts && !needsEnv && !needsNetwork && !hasSvcOverride && !hasHardcodedName && !needsDependsOverride {
		return
	}

	fmt.Fprintf(b, "  %s:\n", svc)

	if hasHardcodedName {
		fmt.Fprintf(b, "    container_name: %s-%s\n", projectName, svc)
	}

	if needsDependsOverride {
		if deps, ok := serviceDepends[svc]; ok {
			var filtered []string
			for _, d := range deps {
				if !disabledSvcs[d] {
					filtered = append(filtered, d)
				}
			}
			if len(filtered) == 0 {
				b.WriteString("    depends_on: !override []\n")
			} else {
				b.WriteString("    depends_on: !override\n")
				for _, d := range filtered {
					fmt.Fprintf(b, "      - %s\n", d)
				}
			}
		} else {
			b.WriteString("    depends_on: !override []\n")
		}
	}

	if svcOv != nil {
		if len(svcOv.Profiles) > 0 {
			b.WriteString("    profiles:\n")
			for _, p := range svcOv.Profiles {
				fmt.Fprintf(b, "      - \"%s\"\n", p)
			}
		}
		if svcOv.MemLimit != "" {
			fmt.Fprintf(b, "    mem_limit: %s\n", svcOv.MemLimit)
		}
	}

	if hasPorts {
		b.WriteString("    ports: !override\n")
		for _, port := range servicePorts[svc] {
			fmt.Fprintf(b, "      - \"%s\"\n", port)
		}
	}

	// Environment
	envMap := make([][2]string, len(resolvedEnv))
	copy(envMap, resolvedEnv)
	if svcOv != nil {
		for k, v := range svcOv.Environment {
			found := false
			for i, kv := range envMap {
				if kv[0] == k {
					envMap[i][1] = v
					found = true
					break
				}
			}
			if !found {
				envMap = append(envMap, [2]string{k, v})
			}
		}
	}
	if len(envMap) > 0 {
		b.WriteString("    environment:\n")
		for _, kv := range envMap {
			fmt.Fprintf(b, "      %s: \"%s\"\n", kv[0], kv[1])
		}
	}

	if len(sharedHosts) > 0 || bindIP != "" {
		b.WriteString("    extra_hosts:\n")
		for _, host := range sharedHosts {
			fmt.Fprintf(b, "      - \"%s:host-gateway\"\n", host)
		}
		if bindIP != "" {
			b.WriteString("      - \"bind.local:host-gateway\"\n")
		}
	}

	if networkName != "" {
		fmt.Fprintf(b, "    networks:\n      - default\n      - %s\n", networkName)
	}
}

func containsStr(ss []string, s string) bool {
	for _, v := range ss {
		if v == s {
			return true
		}
	}
	return false
}
