package services

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

// CopyFiles copies files from repo to worktree based on patterns.
func CopyFiles(repoDir, worktreeDir string, patterns []string) {
	for _, pattern := range patterns {
		if strings.Contains(pattern, "*") {
			matches := globFiles(repoDir, pattern)
			for _, relPath := range matches {
				copySingleFile(filepath.Join(repoDir, relPath), filepath.Join(worktreeDir, relPath))
			}
		} else {
			copySingleFile(filepath.Join(repoDir, pattern), filepath.Join(worktreeDir, pattern))
		}
	}
}

func copySingleFile(src, dest string) {
	info, err := os.Stat(src)
	if err != nil || info.IsDir() {
		return
	}
	if _, err := os.Stat(dest); err == nil {
		return // already exists
	}
	_ = os.MkdirAll(filepath.Dir(dest), 0o755)
	data, err := os.ReadFile(src)
	if err == nil {
		_ = os.WriteFile(dest, data, info.Mode())
	}
}

// ApplyEnvOverrides writes env overrides to env file in dirs containing .env files.
func ApplyEnvOverrides(worktreeDir string, envOverrides []EnvVar, envFileName string) {
	if len(envOverrides) == 0 {
		return
	}
	for _, dir := range findEnvDirs(worktreeDir) {
		allKeys := collectEnvKeys(dir, envFileName)
		lines := []string{"# Auto-generated by tncli. Do not commit."}
		for _, ev := range envOverrides {
			if allKeys[ev.Key] {
				lines = append(lines, ev.Key+"="+ev.Value)
			}
		}
		if len(lines) > 1 {
			_ = os.WriteFile(filepath.Join(dir, envFileName), []byte(strings.Join(lines, "\n")+"\n"), 0o644)
		}
	}
}

func findEnvDirs(worktreeDir string) []string {
	var dirs []string
	if fileExists(filepath.Join(worktreeDir, ".env")) || fileExists(filepath.Join(worktreeDir, ".env.development")) {
		dirs = append(dirs, worktreeDir)
	}
	entries, err := os.ReadDir(filepath.Join(worktreeDir, "apps"))
	if err == nil {
		for _, e := range entries {
			if e.IsDir() {
				appDir := filepath.Join(worktreeDir, "apps", e.Name())
				if fileExists(filepath.Join(appDir, ".env")) {
					dirs = append(dirs, appDir)
				}
			}
		}
	}
	return dirs
}

func collectEnvKeys(dir, excludeFile string) map[string]bool {
	keys := make(map[string]bool)
	entries, err := os.ReadDir(dir)
	if err != nil {
		return keys
	}
	for _, e := range entries {
		name := e.Name()
		if !strings.HasPrefix(name, ".env") || name == excludeFile || e.IsDir() {
			continue
		}
		data, err := os.ReadFile(filepath.Join(dir, name))
		if err != nil {
			continue
		}
		for _, line := range strings.Split(string(data), "\n") {
			line = strings.TrimSpace(line)
			if line == "" || strings.HasPrefix(line, "#") {
				continue
			}
			if key, _, ok := strings.Cut(line, "="); ok {
				keys[strings.TrimSpace(key)] = true
			}
		}
	}
	return keys
}

// WriteEnvFile writes .env.tncli with BIND_IP.
func WriteEnvFile(worktreePath string) error {
	return os.WriteFile(filepath.Join(worktreePath, ".env.tncli"), []byte("BIND_IP=127.0.0.1\n"), 0o644)
}

// EnsureGlobalGitignore sets up global gitignore for tncli files.
func EnsureGlobalGitignore() {
	home, err := os.UserHomeDir()
	if err != nil {
		return
	}
	gitignorePath := filepath.Join(home, ".gitignore_global")

	excludes := ""
	if out, err := exec.Command("git", "config", "--global", "core.excludesfile").Output(); err == nil {
		excludes = strings.TrimSpace(string(out))
	}

	if excludes == "" {
		_ = exec.Command("git", "config", "--global", "core.excludesfile", gitignorePath).Run()
	}

	target := gitignorePath
	if excludes != "" {
		target = excludes
	}
	content, _ := os.ReadFile(target)
	contentStr := string(content)

	tncliFiles := []string{
		"docker-compose.override.yml",
		"docker-compose.shared.yml",
		"dip.override.yml",
		".env.tncli",
		".env.local",
		".env.*.local",
	}
	var toAdd []string
	for _, f := range tncliFiles {
		if !strings.Contains(contentStr, f) {
			toAdd = append(toAdd, f)
		}
	}
	if len(toAdd) > 0 {
		f, err := os.OpenFile(target, os.O_CREATE|os.O_APPEND|os.O_WRONLY, 0o644)
		if err != nil {
			return
		}
		defer f.Close()
		if !strings.Contains(contentStr, "# tncli") {
			fmt.Fprintln(f, "\n# tncli worktree")
		}
		for _, file := range toAdd {
			fmt.Fprintln(f, file)
		}
	}
}

// EnsureNodeBindHost creates ~/.tncli/node-bind-host.js.
func EnsureNodeBindHost() {
	home, err := os.UserHomeDir()
	if err != nil {
		return
	}
	dir := filepath.Join(home, ".tncli")
	_ = os.MkdirAll(dir, 0o755)
	path := filepath.Join(dir, "node-bind-host.js")
	_ = os.WriteFile(path, []byte(`// tncli: monkey-patch net.Server.listen to respect BIND_IP

const net = require('net');
const orig = net.Server.prototype.listen;
net.Server.prototype.listen = function (...args) {
  if (typeof args[0] === 'number' && process.env.BIND_IP) {
    args.splice(1, 0, process.env.BIND_IP);
  }
  return orig.apply(this, args);
};
`), 0o644)
}

// globFiles safely expands a glob pattern relative to repoDir using filepath.Glob.
func globFiles(repoDir, pattern string) []string {
	fullPattern := filepath.Join(repoDir, pattern)
	matches, err := filepath.Glob(fullPattern)
	if err != nil {
		return nil
	}
	var result []string
	for _, m := range matches {
		rel, err := filepath.Rel(repoDir, m)
		if err == nil && !strings.HasPrefix(rel, "..") {
			result = append(result, rel)
		}
	}
	return result
}

// fileExists is a package-local alias for FileExists.
var fileExists = FileExists
